[package]
name = "Examples"
version = "0.0.0"

[addresses]
MyModule = "0x645f3fdfc6afa1a31818fce34c6ab9d26a35d2758bf4163fa587c3c362b75723"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-node-v1.2.0" }